syntax = "proto3";

package geofleet.ride.v1;
import "common/v1/common.proto"; // Import LatLng
import "identity/v1/user.proto"; // Import LatLng
import "google/protobuf/timestamp.proto";

option go_package = "github.com/ducthangng/geofleet-proto/gen/go/geofleet/ride/v1;ridev1";

// RideService focus on the "while" of the service, while users are travelling.
service RideService {
    // Theo dõi nhiều chuyến xe cùng lúc (Server Streaming)
    rpc TrackMultipleRides(TrackMultipleRidesRequest) returns (stream TrackMultipleRidesResponse);

    // Stream from server to clients - can be user / driver / or server admins
    rpc RequestRide(RequestRideRequest) returns (RequestRideResponse);

    // Listen to the dispatcher of the ride_service
    rpc TriggerRideUpdate(TriggerRideUpdateRequest) returns (TriggerRideUpdateResponse);

    // Listen to the dispatcher of the ride_service
    rpc SubscribeRideUpdate(SubscribeRideUpdateRequest) returns (stream SubscribeRideUpdateResponse);

    // This is when the Driver accepts the ride
    rpc AcceptRide(AcceptRideRequest) returns (AcceptRideResponse);

    // This is when the Driver start the ride
    rpc StartRide(StartRideRequest) returns (StartRideResponse);

    // This is when either of users accept the ride
    rpc CancelRide(CancelRideRequest) returns (CancelRideResponse);

    // This is when the driver complete the ride
    rpc CompleteRide(CompleteRideRequest) returns (CompleteRideResponse);
}


enum RideStatus {
    RIDE_STATUS_UNSPECIFIED = 0; // Giá trị mặc định
    RIDE_STATUS_CREATED = 1; // User requested
    RIDE_STATUS_MATCHING = 2; // System pinging drivers
    RIDE_STATUS_ACCEPTED = 3; // Driver accepted
    RIDE_STATUS_ARRIVED = 4; // Driver at pick-up
    RIDE_STATUS_IN_PROGRESS = 5; // In the car
    RIDE_STATUS_COMPLETED = 6; // Arrived destination
    RIDE_STATUS_CANCELLED = 7; // Trip cancelled
}

enum PaymentMethod {
    PAYMENT_METHOD_UNSPECIFIED = 0;
    PAYMENT_METHOD_CASH = 1;
    PAYMENT_METHOD_WALLET = 2;
    PAYMENT_METHOD_CARD = 3;
}


message UniversalRideRequest {
    string ride_id = 1;
    geofleet.common.v1.LatLng current_location = 3;
    google.protobuf.Timestamp created_at = 4;
}

message UniversalRideResponse {
    string ride_id = 1;
    RideStatus ride_status = 2;   
}

message AcceptRideRequest {
    UniversalRideRequest value = 1;
}

message AcceptRideResponse {
    UniversalRideResponse value = 1;
}

message StartRideRequest {
    UniversalRideRequest value = 1;
}

message StartRideResponse {
    UniversalRideResponse value = 1;
}

message CancelRideRequest {
    UniversalRideRequest value = 1;
    string reason = 2;
    string user_id = 3; // who?
    geofleet.identity.v1.UserRole user_role = 4; 
}

message CancelRideResponse {
    UniversalRideResponse value = 1;
    bool is_success = 2;
    string detail = 3;
}

message CompleteRideRequest {
    UniversalRideRequest value = 1;
}

message CompleteRideResponse {
    UniversalRideResponse value = 1;
    double duration_in_second = 2;
    double total_travel_distance_m = 3;
}

message TriggerRideUpdateRequest {
    string ride_id = 1;
    string user_id = 2;
}

message TriggerRideUpdateResponse {
    string ride_id = 1;
    bool is_activated = 2;
    google.protobuf.Timestamp last_updated = 3;
}

message SubscribeRideUpdateRequest {
    string ride_id = 1;
    string user_id = 2;
}

message SubscribeRideUpdateResponse {
    string ride_id = 1;
    bool is_activated = 2;
    google.protobuf.Timestamp last_updated = 3;
}

message RequestRideRequest {
    string user_id = 1;

    geofleet.common.v1.LatLng pickup_point = 2;
    geofleet.common.v1.LatLng dropoff_point = 3;
    geofleet.common.v1.LatLng current_location = 4;
    
    PaymentMethod payment_method = 5;

    RideStatus ride_status = 6;
    google.protobuf.Timestamp created_at = 7;
}

message RequestRideResponse {
    string ride_id = 1;
    string passenger_id = 2;
    string driver_id = 3;
    float estimate_fare = 4;
    float final_fare = 5;
    RideStatus ride_status = 6;
    
    // string cancel_reason = 12; 
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}

message TrackMultipleRidesRequest {
    repeated string ride_ids = 1;
}

message TrackMultipleRidesResponse {
    string ride_id = 1;
    string user_id = 2;
    string driver_id = 3;
    geofleet.common.v1.LatLng current_location = 4;
    double estimated_price = 5;
    string status = 6; // e.g., ON_TRIP, PICKING_UP
}
