syntax = "proto3";

package geofleet.identity.v1;

import "google/protobuf/timestamp.proto"; 
import "buf/validate/validate.proto";
import "common/v1/common.proto";

option go_package = "github.com/ducthangng/geofleet-proto/gen/go/geofleet/identity/v1;identityv1";

enum UserRole {
    USER_ROLE_UNSPECIFIED = 0;
    USER_ROLE_PASSENGER = 1;
    USER_ROLE_DRIVER = 2;
}

service UserService {
    rpc CheckDuplicatedPhone(CheckDuplicatedPhoneRequest) returns (CheckDuplicatedPhoneResponse);
    rpc CreateUserProfile(CreateUserProfileRequest) returns (CreateUserProfileResponse);
    rpc GetUserProfile(GetUserProfileRequest) returns (GetUserProfileResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
}

message CheckDuplicatedPhoneRequest { 
    string phone = 1 [(buf.validate.field).string = {
        pattern: "^[0-9]{10,11}$",
        min_len: 10
    }];
}
message CheckDuplicatedPhoneResponse { bool is_duplicated = 1; }

message LoginRequest {
    string phone = 1 [(buf.validate.field).string.min_len = 10];
    geofleet.common.v1.Password password = 2;
}

message LoginResponse {
    string user_id = 1;
    UserRole role = 2;
    string access_token = 3; // Senior tip: Trả về token thay vì role/address
}

message CreateUserProfileRequest {
  string fullname = 1 [(buf.validate.field).string = {min_len: 3, max_len: 100}];
    
    // 2. Email
    string email = 2 [(buf.validate.field).string.email = true];
    
    // 3. Phone: (Regex)
    string phone = 3 [(buf.validate.field).string = {
        pattern: "^[0-9]{10,11}$",
        min_len: 10
    }];

    // 4. Password: Regex to force Capitalized, number, and special characters
    geofleet.common.v1.Password password = 4;

    string address = 5 [(buf.validate.field).string.min_len = 5];

    // 5. BOD: required and must smaller than this time
    google.protobuf.Timestamp bod = 6 [(buf.validate.field).timestamp = {
        lt_now: true
    }];

    // 6. Role: (UNSPECIFIED)
    UserRole role = 7 [(buf.validate.field).enum = {
        defined_only: true,
        not_in: [0]
    }];
}

message CreateUserProfileResponse {
    string user_id = 1;
}

message GetUserProfileRequest { 
    string user_id = 1 [(buf.validate.field).string.len = 36]; 
}

message GetUserProfileResponse {
    string user_id = 1; // uuid
    string fullname = 2;
    string email = 3;
    string phone = 4;
    string address = 5;
    google.protobuf.Timestamp bod = 6;
    UserRole role = 7;
    double score = 8;
    google.protobuf.Timestamp created_at = 9;
}