syntax = "proto3";

package user.v1;
option go_package = "github.com/ducthangng/geofleet-proto/gen/go/user/v1";

service UserService {
    // 1. Unary: call and receive
    rpc CheckDuplicatedPhone(CheckDuplicatedPhoneRequest) returns (CheckDuplicatedPhoneResponse);

    // 1. Unary: call and receive
    rpc CreateUserProfile(CreateUserProfileRequest) returns (CreateUserProfileResponse);

    // 1. Unary: call and receive
    rpc Login(LoginRequest) returns (LoginResponse);

    // 1. Unary: call and receive
    rpc GetUserProfile(GetUserProfileRequest) returns (GetUserProfileResponse);

    // 2. Server streaming: send a number of data for tracking current rides happening in the service
    rpc TrackMultipleRides(TrackMultipleRidesRequest) returns (stream TrackMultipleRidesResponse);
    
    // 3. Client Streaming: Gửi một loạt tọa độ GPS để lưu lịch sử di chuyển
    rpc UploadLocationHistory(stream UploadLocationHistoryRequest) returns (UploadLocationHistoryResponse);
}

message CheckDuplicatedPhoneRequest {
    string phone = 1;
}

message CheckDuplicatedPhoneResponse {
    int32 is_duplicated = 1; // 0 - 1
}

message LoginRequest {
    string phone = 1;
    string password = 2;
}

message LoginResponse {
    string user_id = 1;
    string address = 2;
    string role = 3;
}

message CreateUserProfileRequest {
    string fullname = 1;
    string email = 2;
    string phone = 3;
    string password = 4;
    string address = 5;
    string bod = 6;
    string role = 7;
    double score = 8;
}

message CreateUserProfileResponse {
    string user_id = 1;
    int32 is_duplicated = 2; // 0 - 1
}

message GetUserProfileRequest {
    string user_id = 1;
}

message GetUserProfileResponse {
    string user_id = 1;
    string fullname = 2;
    string email = 3;
    string phone = 4;
    string address = 5;
    string bod = 6;
    string role = 7;
    double score = 8;
    string date_created = 9;
}

message UploadLocationHistoryRequest {
    double lat = 1;
    double lng = 2;
}

message UploadLocationHistoryResponse {
    string msg = 1;
    int32 count = 2;
}

message TrackMultipleRidesResponse {
    string ride_id = 1;
    string trace_id = 2;
    string user_id = 3;
    string driver_id = 4;
    string start_time_unix = 5;
    string start_location_lat = 6;
    string start_location_lng = 7;
    string destination_lat = 8;
    string destination_lng = 9;
    string estimated_arrival = 10;
    double estimated_price = 11;
    double chosen_payment_method = 12; 
    
}

// Request chứa danh sách các chuyến xe muốn theo dõi
message TrackMultipleRidesRequest {
    repeated string ride_ids = 1;
}