// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneDuplicationCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneDuplicationCheckRequest) Reset() {
	*x = PhoneDuplicationCheckRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneDuplicationCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneDuplicationCheckRequest) ProtoMessage() {}

func (x *PhoneDuplicationCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneDuplicationCheckRequest.ProtoReflect.Descriptor instead.
func (*PhoneDuplicationCheckRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *PhoneDuplicationCheckRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type PhoneDuplicationCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDuplicated  int32                  `protobuf:"varint,1,opt,name=isDuplicated,proto3" json:"isDuplicated,omitempty"` // 0 - 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneDuplicationCheckResponse) Reset() {
	*x = PhoneDuplicationCheckResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneDuplicationCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneDuplicationCheckResponse) ProtoMessage() {}

func (x *PhoneDuplicationCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneDuplicationCheckResponse.ProtoReflect.Descriptor instead.
func (*PhoneDuplicationCheckResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneDuplicationCheckResponse) GetIsDuplicated() int32 {
	if x != nil {
		return x.IsDuplicated
	}
	return 0
}

type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Bod           string                 `protobuf:"bytes,6,opt,name=bod,proto3" json:"bod,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreationRequest) Reset() {
	*x = UserCreationRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreationRequest) ProtoMessage() {}

func (x *UserCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreationRequest.ProtoReflect.Descriptor instead.
func (*UserCreationRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserCreationRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserCreationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCreationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserCreationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserCreationRequest) GetBod() string {
	if x != nil {
		return x.Bod
	}
	return ""
}

func (x *UserCreationRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type UserCreationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDuplicated  int32                  `protobuf:"varint,1,opt,name=isDuplicated,proto3" json:"isDuplicated,omitempty"` // 0 - 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreationResponse) Reset() {
	*x = UserCreationResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreationResponse) ProtoMessage() {}

func (x *UserCreationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreationResponse.ProtoReflect.Descriptor instead.
func (*UserCreationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserCreationResponse) GetIsDuplicated() int32 {
	if x != nil {
		return x.IsDuplicated
	}
	return 0
}

type UserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Bod           string                 `protobuf:"bytes,6,opt,name=bod,proto3" json:"bod,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	DateCreated   string                 `protobuf:"bytes,8,opt,name=date_created,json=dateCreated,proto3" json:"date_created,omitempty"`
	LastLogged    string                 `protobuf:"bytes,9,opt,name=last_logged,json=lastLogged,proto3" json:"last_logged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserResponse) GetBod() string {
	if x != nil {
		return x.Bod
	}
	return ""
}

func (x *UserResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserResponse) GetDateCreated() string {
	if x != nil {
		return x.DateCreated
	}
	return ""
}

func (x *UserResponse) GetLastLogged() string {
	if x != nil {
		return x.LastLogged
	}
	return ""
}

type LocationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationData) Reset() {
	*x = LocationData{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationData) ProtoMessage() {}

func (x *LocationData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationData.ProtoReflect.Descriptor instead.
func (*LocationData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *LocationData) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LocationData) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type UploadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatus) Reset() {
	*x = UploadStatus{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatus) ProtoMessage() {}

func (x *UploadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatus.ProtoReflect.Descriptor instead.
func (*UploadStatus) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UploadStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UploadStatus) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type RideLocation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RideId              string                 `protobuf:"bytes,1,opt,name=ride_id,json=rideId,proto3" json:"ride_id,omitempty"`
	TraceId             string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId              string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId            string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	StartTimeUnix       string                 `protobuf:"bytes,5,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	StartLocationLat    string                 `protobuf:"bytes,6,opt,name=start_location_lat,json=startLocationLat,proto3" json:"start_location_lat,omitempty"`
	StartLocationLng    string                 `protobuf:"bytes,7,opt,name=start_location_lng,json=startLocationLng,proto3" json:"start_location_lng,omitempty"`
	DestinationLat      string                 `protobuf:"bytes,8,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLng      string                 `protobuf:"bytes,9,opt,name=destination_lng,json=destinationLng,proto3" json:"destination_lng,omitempty"`
	EstimatedArrival    string                 `protobuf:"bytes,10,opt,name=estimated_arrival,json=estimatedArrival,proto3" json:"estimated_arrival,omitempty"`
	EstimatedPrice      float64                `protobuf:"fixed64,11,opt,name=estimated_price,json=estimatedPrice,proto3" json:"estimated_price,omitempty"`
	ChosenPaymentMethod float64                `protobuf:"fixed64,12,opt,name=chosen_payment_method,json=chosenPaymentMethod,proto3" json:"chosen_payment_method,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RideLocation) Reset() {
	*x = RideLocation{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RideLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RideLocation) ProtoMessage() {}

func (x *RideLocation) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RideLocation.ProtoReflect.Descriptor instead.
func (*RideLocation) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *RideLocation) GetRideId() string {
	if x != nil {
		return x.RideId
	}
	return ""
}

func (x *RideLocation) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RideLocation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RideLocation) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *RideLocation) GetStartTimeUnix() string {
	if x != nil {
		return x.StartTimeUnix
	}
	return ""
}

func (x *RideLocation) GetStartLocationLat() string {
	if x != nil {
		return x.StartLocationLat
	}
	return ""
}

func (x *RideLocation) GetStartLocationLng() string {
	if x != nil {
		return x.StartLocationLng
	}
	return ""
}

func (x *RideLocation) GetDestinationLat() string {
	if x != nil {
		return x.DestinationLat
	}
	return ""
}

func (x *RideLocation) GetDestinationLng() string {
	if x != nil {
		return x.DestinationLng
	}
	return ""
}

func (x *RideLocation) GetEstimatedArrival() string {
	if x != nil {
		return x.EstimatedArrival
	}
	return ""
}

func (x *RideLocation) GetEstimatedPrice() float64 {
	if x != nil {
		return x.EstimatedPrice
	}
	return 0
}

func (x *RideLocation) GetChosenPaymentMethod() float64 {
	if x != nil {
		return x.ChosenPaymentMethod
	}
	return 0
}

// Request chứa danh sách các chuyến xe muốn theo dõi
type TrackRidesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideIds       []string               `protobuf:"bytes,1,rep,name=ride_ids,json=rideIds,proto3" json:"ride_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackRidesRequest) Reset() {
	*x = TrackRidesRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackRidesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackRidesRequest) ProtoMessage() {}

func (x *TrackRidesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackRidesRequest.ProtoReflect.Descriptor instead.
func (*TrackRidesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *TrackRidesRequest) GetRideIds() []string {
	if x != nil {
		return x.RideIds
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"4\n" +
	"\x1cPhoneDuplicationCheckRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"C\n" +
	"\x1dPhoneDuplicationCheckResponse\x12\"\n" +
	"\fisDuplicated\x18\x01 \x01(\x05R\fisDuplicated\"D\n" +
	"\x10UserLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xbb\x01\n" +
	"\x13UserCreationRequest\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x10\n" +
	"\x03bod\x18\x06 \x01(\tR\x03bod\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\":\n" +
	"\x14UserCreationResponse\x12\"\n" +
	"\fisDuplicated\x18\x01 \x01(\x05R\fisDuplicated\"*\n" +
	"\x0fUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf5\x01\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x10\n" +
	"\x03bod\x18\x06 \x01(\tR\x03bod\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\x12!\n" +
	"\fdate_created\x18\b \x01(\tR\vdateCreated\x12\x1f\n" +
	"\vlast_logged\x18\t \x01(\tR\n" +
	"lastLogged\"2\n" +
	"\fLocationData\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\"6\n" +
	"\fUploadStatus\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xd8\x03\n" +
	"\fRideLocation\x12\x17\n" +
	"\aride_id\x18\x01 \x01(\tR\x06rideId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12&\n" +
	"\x0fstart_time_unix\x18\x05 \x01(\tR\rstartTimeUnix\x12,\n" +
	"\x12start_location_lat\x18\x06 \x01(\tR\x10startLocationLat\x12,\n" +
	"\x12start_location_lng\x18\a \x01(\tR\x10startLocationLng\x12'\n" +
	"\x0fdestination_lat\x18\b \x01(\tR\x0edestinationLat\x12'\n" +
	"\x0fdestination_lng\x18\t \x01(\tR\x0edestinationLng\x12+\n" +
	"\x11estimated_arrival\x18\n" +
	" \x01(\tR\x10estimatedArrival\x12'\n" +
	"\x0festimated_price\x18\v \x01(\x01R\x0eestimatedPrice\x122\n" +
	"\x15chosen_payment_method\x18\f \x01(\x01R\x13chosenPaymentMethod\".\n" +
	"\x11TrackRidesRequest\x12\x19\n" +
	"\bride_ids\x18\x01 \x03(\tR\arideIds2\xb4\x03\n" +
	"\vUserService\x12_\n" +
	"\x14CheckDuplicatedPhone\x12\".user.PhoneDuplicationCheckRequest\x1a#.user.PhoneDuplicationCheckResponse\x12J\n" +
	"\x11CreateUserProfile\x12\x19.user.UserCreationRequest\x1a\x1a.user.UserCreationResponse\x123\n" +
	"\x05Login\x12\x16.user.UserLoginRequest\x1a\x12.user.UserResponse\x12;\n" +
	"\x0eGetUserProfile\x12\x15.user.UserInfoRequest\x1a\x12.user.UserResponse\x12C\n" +
	"\x12TrackMultipleRides\x12\x17.user.TrackRidesRequest\x1a\x12.user.RideLocation0\x01\x12A\n" +
	"\x15UploadLocationHistory\x12\x12.user.LocationData\x1a\x12.user.UploadStatus(\x01B(Z&github.com/ducthangng/geofleet/pb/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*PhoneDuplicationCheckRequest)(nil),  // 0: user.PhoneDuplicationCheckRequest
	(*PhoneDuplicationCheckResponse)(nil), // 1: user.PhoneDuplicationCheckResponse
	(*UserLoginRequest)(nil),              // 2: user.UserLoginRequest
	(*UserCreationRequest)(nil),           // 3: user.UserCreationRequest
	(*UserCreationResponse)(nil),          // 4: user.UserCreationResponse
	(*UserInfoRequest)(nil),               // 5: user.UserInfoRequest
	(*UserResponse)(nil),                  // 6: user.UserResponse
	(*LocationData)(nil),                  // 7: user.LocationData
	(*UploadStatus)(nil),                  // 8: user.UploadStatus
	(*RideLocation)(nil),                  // 9: user.RideLocation
	(*TrackRidesRequest)(nil),             // 10: user.TrackRidesRequest
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.UserService.CheckDuplicatedPhone:input_type -> user.PhoneDuplicationCheckRequest
	3,  // 1: user.UserService.CreateUserProfile:input_type -> user.UserCreationRequest
	2,  // 2: user.UserService.Login:input_type -> user.UserLoginRequest
	5,  // 3: user.UserService.GetUserProfile:input_type -> user.UserInfoRequest
	10, // 4: user.UserService.TrackMultipleRides:input_type -> user.TrackRidesRequest
	7,  // 5: user.UserService.UploadLocationHistory:input_type -> user.LocationData
	1,  // 6: user.UserService.CheckDuplicatedPhone:output_type -> user.PhoneDuplicationCheckResponse
	4,  // 7: user.UserService.CreateUserProfile:output_type -> user.UserCreationResponse
	6,  // 8: user.UserService.Login:output_type -> user.UserResponse
	6,  // 9: user.UserService.GetUserProfile:output_type -> user.UserResponse
	9,  // 10: user.UserService.TrackMultipleRides:output_type -> user.RideLocation
	8,  // 11: user.UserService.UploadLocationHistory:output_type -> user.UploadStatus
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
