// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_CheckDuplicatedPhone_FullMethodName  = "/user.UserService/CheckDuplicatedPhone"
	UserService_CreateUserProfile_FullMethodName     = "/user.UserService/CreateUserProfile"
	UserService_Login_FullMethodName                 = "/user.UserService/Login"
	UserService_GetUserProfile_FullMethodName        = "/user.UserService/GetUserProfile"
	UserService_TrackMultipleRides_FullMethodName    = "/user.UserService/TrackMultipleRides"
	UserService_UploadLocationHistory_FullMethodName = "/user.UserService/UploadLocationHistory"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// 1. Unary: call and receive
	CheckDuplicatedPhone(ctx context.Context, in *PhoneDuplicationCheckRequest, opts ...grpc.CallOption) (*PhoneDuplicationCheckResponse, error)
	// 1. Unary: call and receive
	CreateUserProfile(ctx context.Context, in *UserCreationRequest, opts ...grpc.CallOption) (*UserCreationResponse, error)
	// 1. Unary: call and receive
	Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// 1. Unary: call and receive
	GetUserProfile(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// 2. Server streaming: send a number of data for tracking current rides happening in the service
	TrackMultipleRides(ctx context.Context, in *TrackRidesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RideLocation], error)
	// 3. Client Streaming: Gửi một loạt tọa độ GPS để lưu lịch sử di chuyển
	UploadLocationHistory(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationData, UploadStatus], error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CheckDuplicatedPhone(ctx context.Context, in *PhoneDuplicationCheckRequest, opts ...grpc.CallOption) (*PhoneDuplicationCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhoneDuplicationCheckResponse)
	err := c.cc.Invoke(ctx, UserService_CheckDuplicatedPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUserProfile(ctx context.Context, in *UserCreationRequest, opts ...grpc.CallOption) (*UserCreationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserCreationResponse)
	err := c.cc.Invoke(ctx, UserService_CreateUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserProfile(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, UserService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) TrackMultipleRides(ctx context.Context, in *TrackRidesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RideLocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_TrackMultipleRides_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrackRidesRequest, RideLocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_TrackMultipleRidesClient = grpc.ServerStreamingClient[RideLocation]

func (c *userServiceClient) UploadLocationHistory(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationData, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], UserService_UploadLocationHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationData, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UploadLocationHistoryClient = grpc.ClientStreamingClient[LocationData, UploadStatus]

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	// 1. Unary: call and receive
	CheckDuplicatedPhone(context.Context, *PhoneDuplicationCheckRequest) (*PhoneDuplicationCheckResponse, error)
	// 1. Unary: call and receive
	CreateUserProfile(context.Context, *UserCreationRequest) (*UserCreationResponse, error)
	// 1. Unary: call and receive
	Login(context.Context, *UserLoginRequest) (*UserResponse, error)
	// 1. Unary: call and receive
	GetUserProfile(context.Context, *UserInfoRequest) (*UserResponse, error)
	// 2. Server streaming: send a number of data for tracking current rides happening in the service
	TrackMultipleRides(*TrackRidesRequest, grpc.ServerStreamingServer[RideLocation]) error
	// 3. Client Streaming: Gửi một loạt tọa độ GPS để lưu lịch sử di chuyển
	UploadLocationHistory(grpc.ClientStreamingServer[LocationData, UploadStatus]) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CheckDuplicatedPhone(context.Context, *PhoneDuplicationCheckRequest) (*PhoneDuplicationCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckDuplicatedPhone not implemented")
}
func (UnimplementedUserServiceServer) CreateUserProfile(context.Context, *UserCreationRequest) (*UserCreationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUserProfile not implemented")
}
func (UnimplementedUserServiceServer) Login(context.Context, *UserLoginRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServiceServer) GetUserProfile(context.Context, *UserInfoRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedUserServiceServer) TrackMultipleRides(*TrackRidesRequest, grpc.ServerStreamingServer[RideLocation]) error {
	return status.Error(codes.Unimplemented, "method TrackMultipleRides not implemented")
}
func (UnimplementedUserServiceServer) UploadLocationHistory(grpc.ClientStreamingServer[LocationData, UploadStatus]) error {
	return status.Error(codes.Unimplemented, "method UploadLocationHistory not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CheckDuplicatedPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneDuplicationCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CheckDuplicatedPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CheckDuplicatedPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CheckDuplicatedPhone(ctx, req.(*PhoneDuplicationCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUserProfile(ctx, req.(*UserCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserProfile(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_TrackMultipleRides_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TrackRidesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).TrackMultipleRides(m, &grpc.GenericServerStream[TrackRidesRequest, RideLocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_TrackMultipleRidesServer = grpc.ServerStreamingServer[RideLocation]

func _UserService_UploadLocationHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServiceServer).UploadLocationHistory(&grpc.GenericServerStream[LocationData, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type UserService_UploadLocationHistoryServer = grpc.ClientStreamingServer[LocationData, UploadStatus]

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDuplicatedPhone",
			Handler:    _UserService_CheckDuplicatedPhone_Handler,
		},
		{
			MethodName: "CreateUserProfile",
			Handler:    _UserService_CreateUserProfile_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _UserService_GetUserProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackMultipleRides",
			Handler:       _UserService_TrackMultipleRides_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadLocationHistory",
			Handler:       _UserService_UploadLocationHistory_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "user.proto",
}
